sonar.projectKey=GuilhermeSilva-25_pipeline-calculadora
sonar.organization=48

sonar.sources=.
sonar.exclusions=.venv/**,venv/**,test_*.py,tests/**
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

